version: '3'
rpc:
  listen: 'tcp://127.0.0.1:6001'

server:
  command: 'php vendor/bin/rr-worker start'
  relay: pipes

http:
  address: 0.0.0.0:8080
  access_logs: true
  middleware: [ 'static', 'headers', 'gzip' ]
  pool:
    num_workers: 4
    allocate_timeout: 60s
    destroy_timeout: 1s
    dynamic_allocator:
      max_workers: 25
      spawn_rate: 20
      idle_timeout: 10s
    max_jobs: 100
    supervisor:
      exec_ttl: 120s
      max_worker_memory: 256M
  headers:
    response:
      X-Powered-By: "RoadRunner"
  static:
    dir: "public"
    forbid: [ ".php" ]

jobs:
  consume: [ "default" ]
  pipelines:
    default:
      driver: memory
      config:
        priority: 10
        prefetch: 10

logs:
  level: debug
